version: '2'
services:
    bot:
        build: ./bot
        container_name: bot
        restart: always
    institution_bot:
        build: ./institution_bot
        container_name: institution_bot
        restart: always
    redis:
        image: redis
        container_name: database
        restart: always
        ports:
            - "6379:6379"