version: '2'
services:
    bot:
        build: ./bot
        container_name: bot

    institution_bot:
        build: ./institution_bot
        container_name: institution_bot
    redis:
        image: redis
        container_name: database
        ports:
            - "6379:6379"